kind: Plan
apiVersion: api.ibm.com/v1
metadata:
  name: Bronze Plan
  namespace: LBGDemo
  version: '1.0'
  tags: []
  description: ''
spec:
  qos:
    withQuota:
      plan-limit:
        - $ref: LBGDemo:Quota-fsozv8:1.0
