kind: FreeFlowPolicySequence
apiVersion: api.ibm.com/v1
metadata:
  name: Nano gw
  namespace: LBGDemo
  version: '1.0'
  tags: []
  labels:
    gatewayTypes:
      - nano
spec:
  main:
    - $ref: LBGDemo:default-invoke-policy-Nano gw:1.0
